services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=resurs-ping-pong
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "resurs-ping-pong", "-U", "root"]
      interval: 20s
      timeout: 30s
      retries: 10

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
